/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNI */

#ifndef _Included_com_github_zubnix_jaccall_JNI
#define _Included_com_github_zubnix_jaccall_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    wrap
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_github_zubnix_jaccall_JNI_wrap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    unwrap
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_unwrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    calloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_calloc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    sizeOfPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_sizeOfPointer
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    sizeOfCLong
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_sizeOfCLong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    link
 * Signature: (Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;[B[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_link
  (JNIEnv *, jclass, jstring, jclass, jobjectArray, jbyteArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
