/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNI */

#ifndef _Included_com_github_zubnix_jaccall_JNI
#define _Included_com_github_zubnix_jaccall_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    wrap
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_github_zubnix_jaccall_JNI_wrap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    unwrap
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_unwrap
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    NewGlobalRef
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_NewGlobalRef
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    DeleteGlobalRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_DeleteGlobalRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    GetMethodID
 * Signature: (Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_GetMethodID
  (JNIEnv *, jclass, jclass, jstring, jstring);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    toObject
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_github_zubnix_jaccall_JNI_toObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    calloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_calloc
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    sizeOfPointer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_sizeOfPointer
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    sizeOfCLong
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_sizeOfCLong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    charAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_charAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    shortAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_shortAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    intAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_intAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    longAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_longAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    longLongAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_longLongAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    pointerAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_pointerAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    floatAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_floatAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    doubleAlignment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_doubleAlignment
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_void
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1void
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_sint8
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1sint8
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_uint8
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1uint8
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_sint16
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1sint16
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_uint16
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1uint16
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_sint32
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1sint32
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_uint32
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1uint32
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_slong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1slong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_ulong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1ulong
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_sint64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1sint64
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_uint64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1uint64
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_float
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1float
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_double
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1double
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_pointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1pointer
  (JNIEnv *, jclass);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_struct
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1struct
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_union
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1union
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_type_struct_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1type_1struct_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_callInterface
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1callInterface
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_closure
 * Signature: (JLjava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1closure
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    ffi_closure_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_ffi_1closure_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    link
 * Signature: (Ljava/lang/String;Ljava/lang/Class;[Ljava/lang/String;[B[Ljava/lang/String;[J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_link
  (JNIEnv *, jclass, jstring, jclass, jobjectArray, jbyteArray, jobjectArray, jlongArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    linkFuncPtr
 * Signature: (Ljava/lang/Class;Ljava/lang/String;ILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_linkFuncPtr
  (JNIEnv *, jclass, jclass, jstring, jint, jstring, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readByte
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNI_readByte
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeByte
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeByte
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeBytes
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeBytes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readCLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_readCLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeCLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeCLong
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readDouble
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_zubnix_jaccall_JNI_readDouble
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeDouble
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeDoubles
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeDoubles
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readFloat
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNI_readFloat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeFloat
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeFloat
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeFloats
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeFloats
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNI_readInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeInts
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeInts
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_readLong
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeLong
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeLongs
 * Signature: (J[J)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeLongs
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readPointer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNI_readPointer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writePointer
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writePointer
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readShort
 * Signature: (JI)S
 */
JNIEXPORT jshort JNICALL Java_com_github_zubnix_jaccall_JNI_readShort
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeShort
 * Signature: (JIS)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeShort
  (JNIEnv *, jclass, jlong, jint, jshort);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeShorts
 * Signature: (J[S)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeShorts
  (JNIEnv *, jclass, jlong, jshortArray);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    readString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_zubnix_jaccall_JNI_readString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeString
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeString
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_github_zubnix_jaccall_JNI
 * Method:    writeStruct
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNI_writeStruct
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
