/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNITestUtil */

#ifndef _Included_com_github_zubnix_jaccall_JNITestUtil
#define _Included_com_github_zubnix_jaccall_JNITestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    stuff
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_stuff
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
