/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNITestUtil */

#ifndef _Included_com_github_zubnix_jaccall_JNITestUtil
#define _Included_com_github_zubnix_jaccall_JNITestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    byteArrayAsPointer
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_byteArrayAsPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    pointerOfPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_pointerOfPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readCLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readCLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readDouble
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
