/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNITestUtil */

#ifndef _Included_com_github_zubnix_jaccall_JNITestUtil
#define _Included_com_github_zubnix_jaccall_JNITestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    byteArrayAsPointer
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_byteArrayAsPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    pointerOfPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_pointerOfPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readCLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readCLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readDouble
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execCharTest
 * Signature: (JB)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execCharTest
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnsignedCharTest
 * Signature: (JB)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnsignedCharTest
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execShortTest
 * Signature: (JS)S
 */
JNIEXPORT jshort JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execShortTest
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnsignedShortTest
 * Signature: (JS)S
 */
JNIEXPORT jshort JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnsignedShortTest
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execIntTest
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execIntTest
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnsignedIntTest
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnsignedIntTest
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execLongTest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execLongTest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnsignedLongTest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnsignedLongTest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execLongLongTest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execLongLongTest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnsignedLongLongTest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnsignedLongLongTest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execFloatTest
 * Signature: (JF)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execFloatTest
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execDoubleTest
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execDoubleTest
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execPointerTest
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execPointerTest
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execStructTest
 * Signature: (JJBSJJJF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execStructTest
  (JNIEnv *, jclass, jlong, jlong, jbyte, jshort, jlong, jlong, jlong, jfloat);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execStructTest2
 * Signature: (JJBSJJJF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execStructTest2
  (JNIEnv *, jclass, jlong, jlong, jbyte, jshort, jlong, jlong, jlong, jfloat);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnionTest
 * Signature: (JJIF)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnionTest
  (JNIEnv *, jclass, jlong, jlong, jint, jfloat);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    execUnionTest2
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_execUnionTest2
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    allocStructFp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_allocStructFp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
