/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_zubnix_jaccall_JNITestUtil */

#ifndef _Included_com_github_zubnix_jaccall_JNITestUtil
#define _Included_com_github_zubnix_jaccall_JNITestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    byteArrayAsPointer
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_byteArrayAsPointer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    pointerOfPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_pointerOfPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readCLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readCLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readByte
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readDouble
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readTestStructField0
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readTestStructField0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readTestStructField1
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readTestStructField1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readTestStructField2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readTestStructField2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    readTestStructField3
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_readTestStructField3
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    writeTestStructField0
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_writeTestStructField0
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    writeTestStructField1
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_writeTestStructField1
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     com_github_zubnix_jaccall_JNITestUtil
 * Method:    writeTestStructField3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_github_zubnix_jaccall_JNITestUtil_writeTestStructField3
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
